#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
server_ip=$2
server_username=$3
ssh_key_path=$4

if [[ -z "$ssh_key_path" ]]; then
  ssh_key_path="$HOME/.ssh/id_rsa"
fi

scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$server_username@$server_ip":"$HOME"/
