#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect the requirements:

sudo apt-get -y update && sudo apt-get -y dist-upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
