#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
#sudo service nginx reload
#sudo systemctl restart nginx
