#!/usr/bin/env bash
# a bash script that configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
tmp="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $tmp" /etc/nginx/sites-available/default
sudo service nginx restart
