#!/usr/bin/env bash
# Display "Best School" 10 times, excepting 9th
# which displays Best School and then Hi on a new line.
x=0;
while [ $x -le 10 ];
do
	if (( x == 9 ));
	then
		echo 'Hi'
	else
		echo 'Best School'
	fi
	(( x++ ));
done
